branches:
    only:
        - master
language: php
php:
    - 5.3
    - 5.4
before_script:
    - sudo apt-get update -qq
    - sudo apt-get install -qq openssh-server
    - pecl install ssh2-beta
    - echo "extension=ssh2.so" >> `php --ini | grep "Loaded Configuration" | sed -e "s|.*:\s*||"`
    - sudo useradd --password=test_ssh test_ssh
    - composer --prefer-source --dev install
script: phpunit --coverage-text
