branches:
    only:
        - master
language: php
php:
    - 5.3
    - 5.4
before_script:
    - sudo apt-get update -qq
    - sudo apt-get install -qq openssh-server libssh2-1-dev libssh2-php
    - pecl install -f ssh2-beta < .noninteractive
    - sudo useradd --password=$1$PJ8e9Z97$MNUZR7NXaGQJJ3We8ak8u0 test_ssh
    - composer --prefer-source --dev install
    - export SSH_PORT=`grep Port /etc/ssh/sshd_config | cut -d " " -f2`
    - echo $SSH_PORT
script: phpunit --coverage-text
